KEYWORDS = {
    ("python",): "Python",
    ("html",): "HTML",
    ("css",): "CSS",
    ("javascript", "js"): "JS",
    ("database", "db"): "Data Base",
    ("sql",): "SQL",
    ("django",): "Django",
    ("flask",): "Flask",
    ("jinja2",): "Jinja2",
    ("pyramid",): "Pyramid",
    ("react",): "ReactJS",
    ("angular", "angularjs"): "Angular",
    ("jquery",): "JQuery",
    ("mysql",): "MySQL",
    ("postgresql",): "PostgreSQL",
    ("git",): "GIT",
    ("github",): "GitHub",
    ("mongo", "mongodb"): "MongoDB",
    ("node", "nodejs"): "NodeJS",
    ("vue", "vuejs"): "VueJS",
    ("docker",): "Docker",
    ("rest",): "REST",
    ("django rest", "drf"): "DRF",
    ("fastapi",): "FastAPI",
    ("nosql",): "NoSQL",
    ("celery",): "Celery",
    ("rabbitmq",): "RabbitMQ",
    ("api",): "API",
    ("aws",): "AWS",
    ("linux",): "Linux",
    ("AI", "artificial intelligence"): "AI",
    ("ML", "machine learning"): "ML",
    ("oop",): "OOP",
    ("networking",): "Networking",
    ("fullstack",): "Fullstack",
    ("microservice",): "Microservice",
    ("algorithms",): "Algorithms",
    ("asyncio",): "AsyncIO",
    ("numpy",): "NumPy",
    ("pandas",): "Pandas",
    ("pytest",): "Pytest",
    ("unittest",): "UnitTest",
    ("scraping", "scrape"): "Scraping",
    ("scrapy",): "Scrapy",
    ("selenium",): "Selenium",
}

MONTHES = {
    "січня": 1,
    "лютого": 2,
    "березня": 3,
    "квітня": 4,
    "травня": 5,
    "червня": 6,
    "липня": 7,
    "серпня": 8,
    "вересня": 9,
    "жовтня": 10,
    "листопада": 11,
    "грудня": 12,
}
